pipeline {
    agent any

    tools {
       maven 'maven-3'
       jdk 'java-17'
       NODE_HOME = "/usr/bin/node"
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm git branch: 'roshan', url: 'https://github.com/aitharoshankumar/badam.git'
            }
        }

        stage('Build Frontend') {
            steps {
                dir('frontend/badamshakti-ui') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }

    }
}
