pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'roshan',
                    url: 'https://github.com/aitharoshankumar/badam.git'
            }
        }

        stage('Verify Node & NPM') {
            steps {
                sh 'node -v'
                sh 'npm -v'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('frontend/badamshakti-ui') {
                    sh 'npm install'
                }
            }
        }

        stage('Build Frontend') {
            steps {
                dir('frontend/badamshakti-ui') {
                    sh 'npm run build'
                }
            }
        }
    }

    post {
        success {
            echo 'Frontend build completed successfully'
        }
        failure {
            echo 'Frontend build failed'
        }
    }
}
